### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by alxbouchard** [dcwangmit01/amazon-invoice-downloader#1]
Hi! 
I tried using amazon.ca instead of amazon.com, and the script returned a CAPTCHA request.

Any hints?

Thanks

**Comment by dcwangmit01** [comment]
Captcha may randomly appear if Amazon detects you may be automation, which you are.  Just fill in the Captcha and jump through all of the hoops for logging in, and the script will continue when it detects the following is visible.

locator("a").locator("text=Returns & Orders")
