### ISSUE TITLE
Unable to select year in the order filter

### ISSUE THREAD

**Issue by papley** [dcwangmit01/amazon-invoice-downloader#2]
span.a-dropdown-container is not a sufficiently specific selector, and can find the wrong item.
It also isn't clickable because it's invisible.
Instead select the year directly in the order filter.

    -        page.query_selector('span.a-dropdown-container').click()  # Time Range Dropdown Filter
    -        page.get_by_role("option", name=year).click()  # Select the year (descending order, most recent first)
    +        page.select_option('form[action="/your-orders/orders"] select#time-filter', value=f"year-{year}")

**Comment by dcwangmit01** [comment]
Thank you for the suggestion.  Change made.

https://github.com/dcwangmit01/amazon-invoice-downloader/commit/c7db57f0cc0dbea1b59f264e988bd0925bce6f5a

Will accept PRs as well.
